FROM ubuntu:20.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    mahimahi

RUN apt-get install -y vim

#RUN useradd -u 5566 nosus

#USER nosus
