apiVersion: v1
kind: Service
metadata:
  name: video360-server
spec:
  selector:
    func: video360
  type: NodePort
  ports:
    - port: 5000
      nodePort: 31500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video360-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      func: video360
  template:
    metadata:
      labels:
        func: video360
    spec:
      nodeName: granite
      volumes:
      - name: videodir 
        hostPath:
          path: /home/nosus/workstation/edge/benchmarks/omaf-nginx-server/Garage_gb2
          type: Directory
      - name: videodir-macos
        hostPath:
          path: /home/nosus/workstation/edge/benchmarks/omaf-nginx-server/__MACOSX
          type: Directory
      - name: omaf-js
        hostPath:
          path: /home/nosus/workstation/edge/benchmarks/omaf-nginx-server/omaf.js
          type: Directory
      containers:
      - name: nginx
        image: test:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /usr/share/nginx/html/Garage_gb2
          name: videodir
        - mountPath: /usr/share/nginx/html/__MAXOSX
          name: videodir-macos
        - mountPath: /usr/share/nginx/html/omaf.js
          name: omaf-js
#        command:
#        - /bin/bash
